//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordle_hw.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guesses
    {
        public int Id { get; set; }
        public string WordGuessed { get; set; }
        public string WordToGuess { get; set; }
        public System.DateTime GuessTime { get; set; }
        public int UsersId { get; set; }
    
        public virtual Users User { get; set; }
    }
}
